title: Personal blog
author: Mauro Coppola
email: 
description: > # this means to ignore newlines until "baseurl:"
  Personal blog about development

# social links
twitter_username: 
github_username:  

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
